/**
 * ENEOS Sales Automation - Type Definitions
 * Enterprise-grade type safety for all modules
 */

// ===========================================
// Lead & Customer Types
// ===========================================

export interface Lead {
  date: string;
  customerName: string;
  email: string;
  phone: string;
  company: string;
  industryAI: string;
  website: string | null;
  capital: string | null;
  status: LeadStatus;
  salesOwnerId: string | null;
  salesOwnerName: string | null;
  /** @deprecated Use workflowId — this was Brevo automation workflow_id, not real campaign ID */
  campaignId: string;
  /** Brevo automation workflow_id (renamed from campaignId per ADR-002) */
  workflowId: string;
  /** Actual Brevo campaign ID from campaign_events lookup */
  brevoCampaignId: string | null;
  campaignName: string;
  emailSubject: string;
  source: string;
  leadId: string;
  eventId: string;
  clickedAt: string;
  talkingPoint: string | null;
  closedAt: string | null;
  lostAt: string | null;
  unreachableAt: string | null;
  leadSource: string | null;
  jobTitle: string | null;
  city: string | null;
  // UUID Migration fields (for future Supabase migration)
  leadUUID: string | null;
  createdAt: string | null;
  updatedAt: string | null;
  // Contacted timestamp (when sales claimed the lead)
  contactedAt: string | null;
  // Google Search Grounding fields (added 2026-01-26)
  juristicId: string | null;
  dbdSector: string | null;
  province: string | null;
  fullAddress: string | null;
}

// ===========================================
// Supabase Lead Type (snake_case DB columns)
// ===========================================

export interface SupabaseLead {
  id: string; // UUID
  email: string;
  customer_name: string;
  phone: string;
  company: string;
  industry_ai: string;
  website: string | null;
  capital: string | null;
  status: LeadStatus;
  sales_owner_id: string | null;
  sales_owner_name: string | null;
  workflow_id: string;
  brevo_campaign_id: string | null;
  campaign_name: string;
  email_subject: string;
  source: string;
  lead_id: string;
  event_id: string;
  clicked_at: string | null;
  talking_point: string | null;
  closed_at: string | null;
  lost_at: string | null;
  unreachable_at: string | null;
  contacted_at: string | null;
  version: number;
  lead_source: string | null;
  job_title: string | null;
  city: string | null;
  juristic_id: string | null;
  dbd_sector: string | null;
  province: string | null;
  full_address: string | null;
  created_at: string;
  updated_at: string;
}

/**
 * Convert SupabaseLead (snake_case) → Lead (camelCase)
 * Used by controllers/templates that expect the camelCase Lead interface
 */
export function fromSupabaseLead(s: SupabaseLead): Lead {
  return {
    date: s.created_at,
    customerName: s.customer_name,
    email: s.email,
    phone: s.phone,
    company: s.company,
    industryAI: s.industry_ai,
    website: s.website,
    capital: s.capital,
    status: s.status,
    salesOwnerId: s.sales_owner_id,
    salesOwnerName: s.sales_owner_name,
    campaignId: s.workflow_id, // backward compat
    workflowId: s.workflow_id,
    brevoCampaignId: s.brevo_campaign_id,
    campaignName: s.campaign_name,
    emailSubject: s.email_subject,
    source: s.source,
    leadId: s.lead_id,
    eventId: s.event_id,
    clickedAt: s.clicked_at || '',
    talkingPoint: s.talking_point,
    closedAt: s.closed_at,
    lostAt: s.lost_at,
    unreachableAt: s.unreachable_at,
    leadSource: s.lead_source,
    jobTitle: s.job_title,
    city: s.city,
    leadUUID: s.id,
    createdAt: s.created_at,
    updatedAt: s.updated_at,
    contactedAt: s.contacted_at,
    juristicId: s.juristic_id,
    dbdSector: s.dbd_sector,
    province: s.province,
    fullAddress: s.full_address,
  };
}

/**
 * Convert Partial<Lead> (camelCase) → Supabase insert payload (snake_case)
 * Omits id, created_at, updated_at (auto-generated by DB)
 */
export function toSupabaseLead(lead: Partial<Lead>): Record<string, unknown> {
  const result: Record<string, unknown> = {};
  if (lead.customerName !== undefined) {result.customer_name = lead.customerName;}
  if (lead.email !== undefined) {result.email = lead.email;}
  if (lead.phone !== undefined) {result.phone = lead.phone;}
  if (lead.company !== undefined) {result.company = lead.company;}
  if (lead.industryAI !== undefined) {result.industry_ai = lead.industryAI;}
  if (lead.website !== undefined) {result.website = lead.website;}
  if (lead.capital !== undefined) {result.capital = lead.capital;}
  if (lead.status !== undefined) {result.status = lead.status;}
  if (lead.salesOwnerId !== undefined) {result.sales_owner_id = lead.salesOwnerId;}
  if (lead.salesOwnerName !== undefined) {result.sales_owner_name = lead.salesOwnerName;}
  // Map campaignId → workflow_id (backward compat) or use workflowId directly
  if (lead.workflowId !== undefined) {result.workflow_id = lead.workflowId;}
  else if (lead.campaignId !== undefined) {result.workflow_id = lead.campaignId;}
  if (lead.brevoCampaignId !== undefined) {result.brevo_campaign_id = lead.brevoCampaignId;}
  if (lead.campaignName !== undefined) {result.campaign_name = lead.campaignName;}
  if (lead.emailSubject !== undefined) {result.email_subject = lead.emailSubject;}
  if (lead.source !== undefined) {result.source = lead.source;}
  if (lead.leadId !== undefined) {result.lead_id = lead.leadId;}
  if (lead.eventId !== undefined) {result.event_id = lead.eventId;}
  if (lead.clickedAt !== undefined) {result.clicked_at = lead.clickedAt || null;}
  if (lead.talkingPoint !== undefined) {result.talking_point = lead.talkingPoint;}
  if (lead.leadSource !== undefined) {result.lead_source = lead.leadSource;}
  if (lead.jobTitle !== undefined) {result.job_title = lead.jobTitle;}
  if (lead.city !== undefined) {result.city = lead.city;}
  if (lead.juristicId !== undefined) {result.juristic_id = lead.juristicId;}
  if (lead.dbdSector !== undefined) {result.dbd_sector = lead.dbdSector;}
  if (lead.province !== undefined) {result.province = lead.province;}
  if (lead.fullAddress !== undefined) {result.full_address = lead.fullAddress;}
  return result;
}

export type LeadStatus =
  | 'new'
  | 'claimed'
  | 'contacted'
  | 'closed'
  | 'lost'
  | 'unreachable';

export interface LeadRow extends Lead {
  rowNumber: number;
  version: number;
}

// Valid status values for validation
export const VALID_LEAD_STATUSES: LeadStatus[] = [
  'new',
  'claimed',
  'contacted',
  'closed',
  'lost',
  'unreachable',
];

// ===========================================
// Status History Types
// ===========================================

/**
 * Status History Entry for Google Sheets storage
 * Columns: Lead_UUID, Status, Changed_By_ID, Changed_By_Name, Timestamp, Notes
 * Uses UUID for future Supabase migration compatibility
 */
export interface StatusHistoryEntry {
  leadUUID: string;
  status: LeadStatus;
  changedById: string;
  changedByName: string;
  timestamp: string;
  notes?: string;
}

// ===========================================
// Brevo Webhook Types
// ===========================================

export interface BrevoWebhookPayload {
  event: string;
  email: string;
  id: number;
  date: string;
  ts: number;
  'message-id': string;
  ts_event: number;
  subject: string;
  tag: string;
  sending_ip: string;
  ts_epoch: number;
  contact_id: number;
  campaign_id: number;
  campaign_name: string;
  link?: string;
  // Custom attributes from Brevo
  FIRSTNAME?: string;
  LASTNAME?: string;
  PHONE?: string;
  COMPANY?: string;
  firstname?: string;
  lastname?: string;
  phone?: string;
  company?: string;
}

export interface NormalizedBrevoPayload {
  email: string;
  firstname: string;
  lastname: string;
  phone: string;
  company: string;
  campaignId: string;
  campaignName: string;
  subject: string;
  contactId: string;
  eventId: string;
  clickedAt: string;
  // New fields from Brevo Contact Attributes
  jobTitle: string;
  leadSource: string;
  city: string;
  website: string;
}

// ===========================================
// LINE Types
// ===========================================

export interface LinePostbackData {
  action: LeadStatus;
  /** @deprecated Use leadId instead. Kept for backward compatibility with existing postbacks */
  rowId?: number;
  /** UUID-based lead identifier for future-proof lead lookup */
  leadId?: string;
}

export interface LineWebhookEvent {
  type: string;
  replyToken: string;
  source: {
    type: string;
    userId: string;
    groupId?: string;
  };
  timestamp: number;
  postback?: {
    data: string;
  };
  message?: {
    type: string;
    id: string;
    text?: string;
  };
}

export interface LineWebhookBody {
  destination: string;
  events: LineWebhookEvent[];
}

export interface LineUserProfile {
  userId: string;
  displayName: string;
  pictureUrl?: string;
  statusMessage?: string;
}

// ===========================================
// Gemini AI Types
// ===========================================

export interface CompanyAnalysis {
  industry: string; // Generic category (e.g., "Food & Beverage", "Manufacturing")
  talkingPoint: string;
  website: string | null;
  registeredCapital: string | null;
  keywords: string[];
  // New fields from Google Search grounding
  juristicId: string | null; // เลขทะเบียนนิติบุคคล
  dbdSector: string | null; // DBD Sector code (e.g., F&B-M, MFG-A)
  province: string | null; // จังหวัด (e.g., กรุงเทพมหานคร, เชียงใหม่)
  fullAddress: string | null; // ที่อยู่เต็มของบริษัท (optional)
  // Confidence scoring (Advanced Feature)
  confidence?: number; // 0-100 score indicating classification confidence
  confidenceFactors?: {
    hasRealDomain: boolean; // Domain exists and is valid
    hasDBDData: boolean; // Found official DBD registration
    keywordMatch: boolean; // Matched keyword override rules
    geminiConfident: boolean; // Gemini returned valid DBD sector code
    dataCompleteness: number; // 0-100% of fields populated
  };
}

export interface GeminiAnalysisRequest {
  domain: string;
  companyName: string;
}

// ===========================================
// Google Sheets Types
// ===========================================

export interface SheetConfig {
  spreadsheetId: string;
  leadsSheetName: string;
  dedupSheetName: string;
  salesTeamSheetName: string;
}

/**
 * Legacy SalesTeamMember interface (pre-7-4b)
 * Used by methods that always filter for rows WITH lineUserId (getSalesTeamMember, getSalesTeamAll).
 * For Story 7-4b manual members (lineUserId can be null), use SalesTeamMemberFull instead.
 */
export interface SalesTeamMember {
  lineUserId: string;
  name: string;
  email?: string | null;
  phone?: string | null;
  role?: string; // admin | sales (sales maps to viewer in dashboard)
  createdAt?: string; // ISO 8601 timestamp
  status?: 'active' | 'inactive'; // Team member status for login control
}

/**
 * Extended SalesTeamMember with all fields populated
 * Used by Team Management API (Story 7-4)
 */
export interface SalesTeamMemberFull {
  lineUserId: string | null; // Story 7-4b: Can be null for manually added members
  name: string;
  email: string | null;
  phone: string | null;
  role: 'admin' | 'sales';
  createdAt: string;
  status: 'active' | 'inactive';
}

/**
 * Filter options for getAllSalesTeamMembers
 */
export interface SalesTeamFilter {
  status?: 'active' | 'inactive' | 'all';
  role?: 'admin' | 'sales' | 'all';
}

/**
 * Update payload for updateSalesTeamMember
 */
export interface SalesTeamMemberUpdate {
  email?: string | null;
  phone?: string | null;
  role?: 'admin' | 'sales';
  status?: 'active' | 'inactive';
}

// ===========================================
// API Response Types
// ===========================================

export interface ApiResponse<T = unknown> {
  success: boolean;
  data?: T;
  error?: string;
  message?: string;
}

export interface HealthCheckResponse {
  status: 'healthy' | 'degraded' | 'unhealthy';
  timestamp: string;
  version: string;
  services: {
    supabase: ServiceStatus;
    geminiAI: ServiceStatus;
    lineAPI: ServiceStatus;
  };
  // Cache metadata (optional)
  cached?: boolean;
  cacheAge?: number;
  refreshed?: boolean;
  error?: string;
}

export interface ServiceStatus {
  status: 'up' | 'down' | 'unknown';
  latency?: number;
  lastChecked?: string;
  error?: string;
}

// ===========================================
// Deduplication Types
// ===========================================

export interface DeduplicationRecord {
  key: string;
  email: string;
  campaignId: string;
  processedAt: string;
}

// ===========================================
// Error Types
// ===========================================

export class AppError extends Error {
  constructor(
    message: string,
    public statusCode: number = 500,
    public code: string = 'INTERNAL_ERROR',
    public isOperational: boolean = true
  ) {
    super(message);
    this.name = 'AppError';
    Error.captureStackTrace(this, this.constructor);
  }
}

export class ValidationError extends AppError {
  constructor(message: string) {
    super(message, 400, 'VALIDATION_ERROR');
    this.name = 'ValidationError';
  }
}

export class DuplicateLeadError extends AppError {
  constructor(email: string, leadSource: string) {
    super(`Lead already processed: ${email} from source ${leadSource}`, 409, 'DUPLICATE_LEAD');
    this.name = 'DuplicateLeadError';
  }
}

export class RaceConditionError extends AppError {
  constructor(message: string) {
    super(message, 409, 'RACE_CONDITION');
    this.name = 'RaceConditionError';
  }
}

export class ExternalServiceError extends AppError {
  constructor(service: string, message: string) {
    super(`${service} error: ${message}`, 502, 'EXTERNAL_SERVICE_ERROR');
    this.name = 'ExternalServiceError';
  }
}
